version: "3.3"

services:
  db:
    image: couchbase:enterprise-6.5.0
    deploy:
      replicas: 1
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210

  daga-session-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7200:7200
    depends_on:
      - "db"
